### ISSUE TITLE
surface: command not found

### ISSUE THREAD

**Issue by Hustwireless** [qzed/linux-surface-control#2]
Hi, qzed!
First, thank you for your hard work to provide us this convenient command line tool!
I want to try it so I downloaded it and build from source on my surfacebook2. However, I'm not familiar with cargo and rust, I followed the instructions in the README file, and get this output:
```
...
Finished dev [unoptimized + debuginfo] target(s) in 16.19s                  
     Running `target/debug/surface`

surface 0.2.1
Maximilian Luz <luzmaximilian@gmail.com>
Control various aspects of Microsoft Surface devices

USAGE:
    surface [FLAGS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -q, --quiet      Keep output quiet
    -V, --version    Prints version information

SUBCOMMANDS:
    dgpu           Control or query the dGPU power state on the Surface Book 2
    help           Prints this message or the help of the given subcommand(s)
    latch          Control the latch/dtx-system on the Surface Book 2
    performance    Control or query the current performance-mode
    status         Query the current system status

```
But when I tried to type some commands to see whether it works, I got the "surface: command not found" information. I'm not very clear about how to set it up. Would you please help me with it? Thanks~

**Comment by qzed** [comment]
This is because the program cannot be found via the `PATH` variable, e.g. because it has not been installed yet.

When building from source you've got multiple options. If you're on debian, you can run cargo deb (provided you have the cargo-deb extension installed which can be done via `cargo install cargo-deb`) which will give you a .deb package in `target/debian`, which you can then install with `dpkg`. If you're on Arch, you can use the PKGBUILD from this repo.

On any distribution, running `cargo install` can install the program under your local user, i.e. to `~/.cargo/bin` if not specified otherwise. In this case you have to add that path to your `PATH` variable. The way to do that depends on the shell you use.

For testing/experimenting you can also run the executable directly from the project directory running `cargo run -- <args>`. Note that the `--` is required to separate arguments to `cargo` from arguments to the surface executable and the `--release` is optional. This seems to be what you've done already. This does nothing more than making sure the executable is up to date and then run it. The executable itself can be found under `target/<target>/surface`, where `<target>` is either `debug` or `release`.

If you want to create a new package, you can also have a look at [`pkg/arch/PKGBUILD`](https://github.com/qzed/linux-surface-control/blob/b9402e2ccf9fe9b3fef160e131aad2f308e056a0/pkg/arch/PKGBUILD) which contains all the required commands to build and install the program and completion-files for zsh/bash/fish in the respective functions (note that the paths for the completion files may be different for your distribution).

**Comment by Hustwireless** [comment]
Thank you very much!
I forgot to tell you that my linux distribution is ubuntu, but I followed your instructions on any distribution and run `cargo install --path [path to linux-surface-control]` and successfully installed it! It's really cool!

And these two websites told me about what the argument '--path' mean:
https://www.systutorials.com/docs/linux/man/1-cargo-install/
https://stackoverflow.com/questions/25233487/what-is-the-intended-planned-way-of-configuring-installing-software-that-uses-ru

Then I add PATH variable to my shell, follow the answers here:
https://stackoverflow.com/questions/11530090/adding-a-new-entry-to-the-path-variable-in-zsh

Actually I'm pretty new to computer science field, and I've spent some time to figure out what cargo is. Is it something for rusty just like the cmake to c++? And finally, does create a new package means to develop a sub command based on this project?
Thanks~

**Comment by qzed** [comment]
Since you're on Ubuntu I'd actually recommend installing the .deb file (unless you have some reason not to). I should probably update the readme and mention Ubuntu there.

> I've spent some time to figure out what cargo is. Is it something for rusty just like the cmake to c++?

You could compare it that way, yes. Although I'd say there's a bit of a difference where cargo is _the_ standard tool provided by the rust dev team itself, whereas cmake is _one of many_ build tools provided by others. It's more like pip for python.

> does create a new package means to develop a sub command based on this project?

No, what I meant by that was that, if you were using e.g. fedora (or any other distribution I don't provide a ready-to-install package for), you could create a package for it which you can then install via the package-manager of that distribution.

**Comment by Hustwireless** [comment]
Yes, I actually tried .deb releases at first, but maybe there's some problem with my Ubuntu. Every time I double click a .deb file to install it, the "Ubuntu software" (something like app store) will open and the Install button won't work, and thus I have to download the source file and try to build and install it.

And thank you for your explanations, I can now fully understand your answers.

P.S. I wonder if I could ask something not very related to this issue... That is, how to systematically understand what the build tools & the operating system are doing, and finally can do some interesting things like writing these applications just like you are doing? I find myself learning all these things in fragmentation and usually don't understand the relations between them, e.g. answers on stackoverflow.com. 
I know this might be a really really large topic... I'll be really grateful if you'd like to provide a general path.

**Comment by qzed** [comment]
Can you try and install it via `sudo dpkg -i <path-to-.deb>` if this doesn't work it should give a bit more information why.

I can try, the best place to discuss that would probably be gitter.

**Comment by Hustwireless** [comment]
Yes, the output shows that some dependency problems occurred.
```
dpkg: dependency problems prevent configuration of surface:
 surface depends on libc6 (>= 2.28); however:
  Version of libc6:amd64 on system is 2.23-0ubuntu10.
 surface depends on libgcc1 (>= 1:8.3.0); however:
  Version of libgcc1:amd64 on system is 1:6.0.1-0ubuntu1.

dpkg: error processing package surface (--install):
 dependency problems - leaving unconfigured
```
I then tried `sudo apt-get install libc6`, and it prompts:
```
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libc6-dbg : Depends: libc6 (= 2.23-0ubuntu10) but 2.23-0ubuntu11 is to be installed
 libc6-dev : Depends: libc6 (= 2.23-0ubuntu10) but 2.23-0ubuntu11 is to be installed
 libc6-i386 : Depends: libc6 (= 2.23-0ubuntu10) but 2.23-0ubuntu11 is to be installed
 surface : Depends: libc6 (>= 2.28) but 2.23-0ubuntu11 is to be installed
           Depends: libgcc1 (>= 1:8.3.0) but 1:6.0.1-0ubuntu1 is to be installed
```
I have no idea about whether it is safe to run `apt-get -f install `, will it affect other applications which depend on old version packages?

**Comment by qzed** [comment]
Ah, I see. I don't think `-f` is going to work here, in any case I wouldn't recommend it. The dependencies on `libc6` and `libgcc1` are added implicitly by `cargo-deb`, and I believe are determined by the current versions installed on my build container (debian-buster). These libraries are pretty much guaranteed to be backward-compatible, so I'll probably try to set up an older debian version, which should fix this.

**Comment by Hustwireless** [comment]
Ah, because my email didn't show the whole comments, I've just read the Edit: part just now. I'll try it tomorrow. Thanks!

**Comment by qzed** [comment]
@Hustwireless Okay, I've rebuilt the package on a Debian 8 container and replaced it on the latest release. Requirements are now `libgcc1 >= 1:4.9.2` and `libc6 >= 2.19`, so it should work on your system now, if you want to give it a try.

**Comment by Hustwireless** [comment]
Yes, I tried cargo clean and it works in zsh. And this showed that if I didn't learn things systematically, I might end up guessing it and would not know the true reasons that lay behind.
Besides, would it be safe to dpkg the new release without remove the previous one? Will the command deal with it automatically?

**Comment by Hustwireless** [comment]
I tried, it works automatically. And the new release works very well. It's very nice of you to be so patient, thank you very much!

**Comment by qzed** [comment]
Guessing is usually a good start, the rest comes with experience and curiosity, so always keep asking questions!

> would it be safe to dpkg the new release without remove the previous one?

Yes (as you've figured out), the standard package management tools take the usual cases (e.g. package-upgrade, re-install) into account.

Awesome that it's working now!
